FROM --platform=$BUILDPLATFORM node:20-alpine AS base

# Deps — runs on build machine (amd64), fast
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# Build — also runs natively on build machine, no QEMU
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ARG NEXT_PUBLIC_CHAIN_ID=421614
ARG NEXT_PUBLIC_RPC_URL=https://sepolia-rollup.arbitrum.io/rpc
ARG NEXT_PUBLIC_DEMO_ASSET_ADDRESS
ARG NEXT_PUBLIC_DEMO_CONFIDENTIAL_WRAPPER_ADDRESS
ARG NEXT_PUBLIC_DEMO_FAUCET_ADDRESS
ARG NEXT_PUBLIC_VAULT_CONTRACT_ADDRESS
ARG NEXT_PUBLIC_RWA_GOLD_ASSET
ARG NEXT_PUBLIC_RWA_GOLD_WRAPPER
ARG NEXT_PUBLIC_RWA_PLATINUM_ASSET
ARG NEXT_PUBLIC_RWA_PLATINUM_WRAPPER
ARG NEXT_PUBLIC_RWA_OIL_ASSET
ARG NEXT_PUBLIC_RWA_OIL_WRAPPER
ARG NEXT_PUBLIC_RWA_DIAMOND_ASSET
ARG NEXT_PUBLIC_RWA_DIAMOND_WRAPPER
ARG NEXT_PUBLIC_RWA_SILVER_ASSET
ARG NEXT_PUBLIC_RWA_SILVER_WRAPPER
ARG NEXT_PUBLIC_RWA_RARE_EARTH_ASSET
ARG NEXT_PUBLIC_RWA_RARE_EARTH_WRAPPER

ENV NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID \
    NEXT_PUBLIC_CHAIN_ID=$NEXT_PUBLIC_CHAIN_ID \
    NEXT_PUBLIC_RPC_URL=$NEXT_PUBLIC_RPC_URL \
    NEXT_PUBLIC_DEMO_ASSET_ADDRESS=$NEXT_PUBLIC_DEMO_ASSET_ADDRESS \
    NEXT_PUBLIC_DEMO_CONFIDENTIAL_WRAPPER_ADDRESS=$NEXT_PUBLIC_DEMO_CONFIDENTIAL_WRAPPER_ADDRESS \
    NEXT_PUBLIC_DEMO_FAUCET_ADDRESS=$NEXT_PUBLIC_DEMO_FAUCET_ADDRESS \
    NEXT_PUBLIC_VAULT_CONTRACT_ADDRESS=$NEXT_PUBLIC_VAULT_CONTRACT_ADDRESS \
    NEXT_PUBLIC_RWA_GOLD_ASSET=$NEXT_PUBLIC_RWA_GOLD_ASSET \
    NEXT_PUBLIC_RWA_GOLD_WRAPPER=$NEXT_PUBLIC_RWA_GOLD_WRAPPER \
    NEXT_PUBLIC_RWA_PLATINUM_ASSET=$NEXT_PUBLIC_RWA_PLATINUM_ASSET \
    NEXT_PUBLIC_RWA_PLATINUM_WRAPPER=$NEXT_PUBLIC_RWA_PLATINUM_WRAPPER \
    NEXT_PUBLIC_RWA_OIL_ASSET=$NEXT_PUBLIC_RWA_OIL_ASSET \
    NEXT_PUBLIC_RWA_OIL_WRAPPER=$NEXT_PUBLIC_RWA_OIL_WRAPPER \
    NEXT_PUBLIC_RWA_DIAMOND_ASSET=$NEXT_PUBLIC_RWA_DIAMOND_ASSET \
    NEXT_PUBLIC_RWA_DIAMOND_WRAPPER=$NEXT_PUBLIC_RWA_DIAMOND_WRAPPER \
    NEXT_PUBLIC_RWA_SILVER_ASSET=$NEXT_PUBLIC_RWA_SILVER_ASSET \
    NEXT_PUBLIC_RWA_SILVER_WRAPPER=$NEXT_PUBLIC_RWA_SILVER_WRAPPER \
    NEXT_PUBLIC_RWA_RARE_EARTH_ASSET=$NEXT_PUBLIC_RWA_RARE_EARTH_ASSET \
    NEXT_PUBLIC_RWA_RARE_EARTH_WRAPPER=$NEXT_PUBLIC_RWA_RARE_EARTH_WRAPPER

RUN npm run build

# Production image — THIS stage uses the target platform (arm64 on Pi)
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs && \
    mkdir -p ./public

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]
